name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APP_VERSION: 1.0.0.${{ github.run_number }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Application version
      run: |
        echo "${{ env.APP_VERSION }}"
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
        source-url: https://nuget.pkg.github.com/crip-home/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: dotnet restore -v m
    - name: Build solution
      run: dotnet build --no-restore -c Debug -v m
    - name: Test Crip.AspNetCore.Logging.Tests
      run: dotnet test --no-restore --no-build -v n
    - name: Build Crip.AspNetCore.Logging
      run: dotnet build Crip.AspNetCore.Logging/Crip.AspNetCore.Logging.csproj -c Release --no-restore -p:Version=${{ env.APP_VERSION }}
    - name: Pack NuGet
      run: dotnet pack Crip.AspNetCore.Logging/Crip.AspNetCore.Logging.csproj -c Release --no-build --include-source -p:PackageVersion=${{ env.APP_VERSION }}
    - name: Publish NuGet
      run: dotnet nuget push "Crip.AspNetCore.Logging/bin/Release/Crip.AspNetCore.Logging.${{ env.APP_VERSION }}.nupkg"
